### ISSUE TITLE
TemplateProcessingException while sending confirmation mail

### ISSUE THREAD

**Issue by mausumi345** [thymeleaf/thymeleaf-itutorial#11]
I am getting below error.I have tried with thymeleaf-spring3 version 2.0.18..Still facing same issue.Error i am getting while sending confirmation mail after check out
HTTP Status 500 - Request processing failed; nested exception is org.springframework.mail.MailPreparationException: Could not prepare mail; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "customer.firstName + ' ' + customer.lastName" (orderConfirmation-email:19).

Please let me know how to fix this.

Thanks
Mausumi

**Comment by jmiguelsamper** [comment]
I think this issue is not related to the Interactive Tutorial. Please use the forums.
