### ISSUE TITLE
Switch to Heroku

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-itutorial#12]
I think we should try switching to Heroku (by moving http://itutorial.thymeleaf.org there) and see whether it correctly handles our traffic for this tutorial.

If after a time everything goes OK, the current paid hosting could be shut down.

**Comment by jmiguelsamper** [comment]
I've just configured that domain in Heroku. You can change the DNS entry whenever you want.

**Comment by danielfernandez** [comment]
To what value?

**Comment by jmiguelsamper** [comment]
Sorry, I forgot to say that, according to
    https://devcenter.heroku.com/articles/custom-domains
the DNS entry should be a CNAME entry pointing to
    thymeleaf-itutorial.herokuapp.com

**Comment by danielfernandez** [comment]
Done!

**Comment by jmiguelsamper** [comment]
Ok, it works with the updated DNS value.

Let's see in a few days if everything is working OK.

**Comment by jmiguelsamper** [comment]
The tutorial is working all right at Heroku, so it can be kept that way.

Added a link to Heroku in the "about" page.
