### ISSUE TITLE
Mention Thymeleaf as a technology in the "about" section

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-itutorial#16]
At the _about_ section, this can be read:

---

This interactive tutorial has been created by the Thymeleaf Team using great open source tools like:
- ACE web editor
- Adobe Source Code Pro font
- jQuery
- Spring Framework

---

Hmmm... and Thymeleaf? ;-)

**Comment by jmiguelsamper** [comment]
I assumed that everybody would make an educated guess about it.

**Comment by ultraq** [comment]
lol, Thymeleaf is kind of a given.

**Comment by jmiguelsamper** [comment]
Explicitely mentioned now.

**Comment by danielfernandez** [comment]
hehe, for many years everybody made an educated guess about Hotmail being run by Microsoft on Windows... yet it was FreeBSD :-D

Nah, it's just that a list of "great open source tools" definitely must contain thymeleaf ;-)

Thanks!
