### ISSUE TITLE
Tutorial does not work with Thymeleaf 2.0.17+

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf-itutorial#6]
The tutorial app breaks where upgrading to Thymeleaf 2.0.17 or higher.

The problem happens at parsing and executing the template.

**Comment by danielfernandez** [comment]
Have you confirmed whether this is a bug in the template or a bug in thymeleaf?

**Comment by jmiguelsamper** [comment]
I'm not sure yet.

The problem with newer versions is that model attributes are not recognized
- _org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "product"_

Maybe there are changes in the creation of WebContext object in this versions. This is where I create the WebContext object:
- https://github.com/thymeleaf/thymeleaf-itutorial/blob/2.0-dev/src/main/java/org/thymeleaf/itutorial/TemplateExecutor.java

I can reproduce the problem with the test:
- https://github.com/thymeleaf/thymeleaf-itutorial/blob/2.0-dev/src/test/java/org/thymeleaf/tools/memoryexecutor/StaticTemplateExecutorTest.java
  just replacing line 49 by

``` java
        WebContext context = new WebContext(new MockHttpServletRequest(), new MockHttpServletResponse(), new MockServletContext());
```

(using spring-test mock objects).

**Comment by danielfernandez** [comment]
Hmmm... in your test, there is no `\n` after the DOCTYPE clause of your template... though there is one in your result. Could that be related?

**Comment by jmiguelsamper** [comment]
No, the test works OK with Thymeleaf 2.0.16, and with 2.0.17 fails with
- _Exception evaluating SpringEL expression: "greeting"_

i've just uploaded the code of the test to reproduce the error. Just changing Thymeleaf version in pom.xml will make the test fail or pass:
- https://github.com/thymeleaf/thymeleaf-itutorial/blob/2.0-dev/src/test/java/org/thymeleaf/tools/memoryexecutor/StaticTemplateExecutorTest.java

About the `\n`, yes, it is a strange behavoir, but I did not want to investigate it further when I saw it for the first time. But you can see it in every exercise in the tutorial, the "generated source" box always has an extra newline after DOCTYPE.

**Comment by jmiguelsamper** [comment]
The `\n` after DOCTYPE issue seems to happen in all my websites in production. See, for example, http://www.ticnologic.com/ or the home page of http://thymeleaf-itutorial.appspot.com/

Do you want me to report in the issue tracker?

**Comment by danielfernandez** [comment]
The exception underneath is:

```
Caused by: java.lang.NullPointerException
    at org.thymeleaf.spring3.expression.Themes.<init>(Themes.java:53)
    at org.thymeleaf.spring3.expression.SpelVariableExpressionEvaluator.computeExpressionObjects(SpelVariableExpressionEvaluator.java:165)
    at org.thymeleaf.spring3.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:88)
    ... 57 more
```

This is solved in 2.0.18: See thymeleaf/thymeleaf-spring3#26

**Comment by ultraq** [comment]
D'oh!  The themes object comes back to haunt us :frowning:

**Comment by jmiguelsamper** [comment]
I'm sorry but it also fails with version 2.0.18. Do I have to modify anything in my code?

**Comment by danielfernandez** [comment]
Hmmm are you sure? your test executes OK with 2.0.18 for me...

**Comment by jmiguelsamper** [comment]
Oh, I'm puzzled now!

I tried it several times, invoking the test both from the command line and from Netbeans and it fails with 2.0.17, 2.0.18 and 2.0.19-SNAPSHOT but works with 2.0.16.

I cleared my maven cache.

I've even uploaded a version with 2.0.18 to GAE and it fails, press the "Apply solution" button at http://thymeleaf-itutorial.appspot.com/exercise/1

**Comment by danielfernandez** [comment]
Hmmm... can you make sure you are using `thymeleaf-spring3-2.0.18` and not only `thymeleaf-2.0.18`? Note that this fix was in `thymeleaf-spring3`...

**Comment by jmiguelsamper** [comment]
Yes, I'm really sure.

I'll try to do a fresh installation in another computer.

**Comment by danielfernandez** [comment]
Got it. This is my fault.

Somehow I created a 2.0.18 distribution .jar for `thymeleaf-spring3` with exactly the same contents as 2.0.17. No commits applied. I cannot understand how come I did this... but it's a fact I did. I have to investigate.

And all tests went perfectly OK because they execute on SNAPSHOT versions, and both the last 2.0.18-SNAPSHOT and the first 2.0.19-SNAPSHOT versions contain the fix for that `Themes` bug.

So weird. I cannot imagine how this was even possible...

I'm afraid I'll have to reopen the issue and release 2.0.19 really soon. Darn :-(

**Comment by danielfernandez** [comment]
2.0.18 works. No packaging issue. There must be another reason why this is being raised at itutorial... seems as is your `Context` object is being mistaken for an `IWebContext` object...

**Comment by jmiguelsamper** [comment]
The problem is probably due to the inexistence of a Spring RequestContext object in the WebContext object, at least in the test.

Maybe we can mock this object using some of the techiques used in [1](https://github.com/thymeleaf/thymeleaf-testing/blob/2.1-master/src/main/java/org/thymeleaf/testing/templateengine/context/web/SpringWebProcessingContextBuilder.java) and [2](https://github.com/thymeleaf/thymeleaf-testing/blob/2.1-master/src/main/java/org/thymeleaf/testing/templateengine/context/web/WebProcessingContextBuilder.java)

The NullPointerException is thrown in [Themes.java](https://github.com/thymeleaf/thymeleaf-spring3/blob/2.1-dev/src/main/java/org/thymeleaf/spring3/expression/Themes.java) constructor.

**Comment by jmiguelsamper** [comment]
Finally the problem was worked around by setting manually the Spring's RequestContext object needed by the [Themes.java](https://github.com/thymeleaf/thymeleaf-spring3/blob/2.1-dev/src/main/java/org/thymeleaf/spring3/expression/Themes.java) constructor.

**Comment by mausumi345** [comment]
I am getting below error.I have tried with  thymeleaf-spring3 version 2.0.18..Still facing same issue.Error i am getting while sending confirmation mail after check out
HTTP Status 500 - Request processing failed; nested exception is org.springframework.mail.MailPreparationException: Could not prepare mail; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "customer.firstName + ' ' + customer.lastName" (orderConfirmation-email:19).

Please let me know how to fix this.

Thanks

**Comment by jmiguelsamper** [comment]
I think this issue is not related to the Interactive Tutorial. Please use the forums.
